### ISSUE TITLE
Location Markup w/ Tooltip

### ISSUE THREAD

**Issue by jrceno** [databyss-org/databyss#327] opened 2020-07-20 09:53 UTC
When you open the tooltip and then click location, the text only turns light grey when you click out of the tooltip. The same thing doesn't happen when you click bold and italics.

**Comment by pzhine** [comment] 2020-08-01 12:56
(just on Jake's computer for now)

**Comment by pzhine** [comment] 2020-08-17 16:33
If we can't reproduce this locally or on Sauce virtual browsers, close it for now

**Closed** 2020-08-25 22:22 UTC
Labels: bug
