### ISSUE TITLE
Fix Recentering on Longer Paragraphs

### ISSUE THREAD

**Issue by jrceno** [databyss-org/databyss#316] opened 2020-07-10 17:27 UTC
A couple times, when I edit long paragraphs in the midst of a lot of text, the selection cursor messes up a little. I believe the beginning of this occurs because the editor recenters its focus when you start typing in a long paragraph. It shouldn't do that. I believe after that, recentering, the cursor itself ocassionally loses its place.

**Comment by pzhine** [comment] 2020-08-01 13:07
duplicate of #321

**Closed by pzhine** 2020-08-01 13:07 UTC
Labels: bug
